Update

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,6 +3,7 @@ image: cirrusci/flutter:stable
 stages:
   - lint
   - test
+  - publish
 
 .projects: &projects
   parallel:
@@ -93,3 +94,87 @@ swift_analyze:
 #       - ./**/lib/**/*.dart
 #       - ./**/test/**/*.dart
 #       - .gitlab-ci.yml
+
+dry_run:
+  <<: *projects
+  stage: publish
+  script:
+    - cd "${PROJECT}"
+    - flutter pub get
+    - flutter pub publish --dry-run
+  only:
+    refs:
+      - merge_requests
+
+.pub_dev_publish: &pub_dev_publish
+  # https://robertohuertas.com/2019/01/20/publish-flutter-package-with-travis/
+  stage: publish
+  script:
+    - |
+      cd "${PROJECT}"
+      if [ -z "${PUB_DEV_PUBLISH_ACCESS_TOKEN}" ]; then
+        echo "Missing PUB_DEV_PUBLISH_ACCESS_TOKEN environment variable"
+        exit 1
+      fi
+
+      if [ -z "${PUB_DEV_PUBLISH_REFRESH_TOKEN}" ]; then
+        echo "Missing PUB_DEV_PUBLISH_REFRESH_TOKEN environment variable"
+        exit 1
+      fi
+
+      if [ -z "${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}" ]; then
+        echo "Missing PUB_DEV_PUBLISH_TOKEN_ENDPOINT environment variable"
+        exit 1
+      fi
+
+      if [ -z "${PUB_DEV_PUBLISH_EXPIRATION}" ]; then
+        echo "Missing PUB_DEV_PUBLISH_EXPIRATION environment variable"
+        exit 1
+      fi
+
+      cat <<EOF > ~/.pub-cache/credentials.json
+      {
+        "accessToken":"$(echo "${PUB_DEV_PUBLISH_ACCESS_TOKEN}" | base64 -d)",
+        "refreshToken":"$(echo "${PUB_DEV_PUBLISH_REFRESH_TOKEN}" | base64 -d)",
+        "tokenEndpoint":"${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}",
+        "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
+        "expiration":${PUB_DEV_PUBLISH_EXPIRATION}
+      }
+      EOF
+    - flutter pub get
+    - flutter pub publish -f
+  except:
+    refs:
+      - branches
+
+multi_window_publish:
+  <<: *pub_dev_publish
+  variables:
+    - PROJECT: "multi_window"
+  only:
+    refs:
+      - /^multi_window-v.*$/
+
+multi_window_interface_publish:
+  <<: *pub_dev_publish
+  variables:
+    - PROJECT: "multi_window_interface"
+  only:
+    refs:
+      - /^multi_window_interface-v.*$/
+
+multi_window_linux_publish:
+  <<: *pub_dev_publish
+  variables:
+    - PROJECT: "multi_window_linux"
+  only:
+    refs:
+      - /^multi_window_linux-v.*$/
+
+multi_window_macos_publish:
+  <<: *pub_dev_publish
+  variables:
+    - PROJECT: "multi_window_macos"
+  only:
+    refs:
+      - /^multi_window_macos-v.*$/
